### PR TITLE
Made property filter component configurable via App Builder

### PR DESCRIPTION
**Pull request by pozil**
I removed the hard-coded max value for the property price slider and replaced it with an App Builder param. This is a small code modification and adds a much needed example.

### CODE REVIEW

**Comment by pozil** [comment]
@muenzpraeger why did you close this PR? Isn't it still relevant?

**Comment by muenzpraeger** [comment]
The use case for this component is to show prices in a defined range, based on what this sample app defines as data. There's no reason to have this configurable.

**Comment by pozil** [comment]
In a real world scenario you would need something configurable for the slider max value.
The problem I tried to solve here is to provide an example of an App Builder parameter. AFAIK we don't have that in our samples.

**Comment by muenzpraeger** [comment]
Easy Spaces and LWC Recipes have that, for example.

**Comment by pozil** [comment]
Ok fine. Let's scrap that then.

**Pull request closed without merging**
